name: Build

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  actions: write
  pull-requests: write

run-name: Build from ${{ github.ref }}

jobs:
  formatting-tests:
    name: Consistency and formatting
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python: ["3.10", "3.11", "3.12"]
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: ${{ matrix.python }}

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: poetry sync

      - name: Formatting
        run: poetry run poe format

      - name: Linting
        run: poetry run poe lint

      - name: Type checking
        run: poetry run poe types

      - name: Dependency checks
        run: poetry run poe deps

      - name: License compliance
        run: poetry run poe licenses

      - name: Security scan
        run: poetry run poe vuln

  unit-tests:
    name: Unit Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python: ["3.10", "3.11", "3.12"]
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.x
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: poetry sync

      - name: Tests with coverage
        run: poetry run poe test

      - name: Upload coverage reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-${{ matrix.python }}
          path: |
            coverage.xml
            htmlcov/

